INSERT INTO PERSON_INFO_ALL 
SELECT P.PID,
  P.AGEP,
  P.SEX,
  PI.HOME_ZIPCODE,
  H.HINCP,
  H.HID,
  H.PERSONS
FROM PROTOPOP.KS_PERSON_2009_1 P,
  PROTOPOP.KS_PERSON_INFO_2009_1 PI,
  PROTOPOP.KS_HOUSEHOLD_2009_1 H,
  (SELECT HID,
	    PID
	  FROM
	    (SELECT HID,
		      PID,
		      ROW_NUMBER() OVER (PARTITION BY HID ORDER BY 1) AS RNUM
		    FROM PROTOPOP.KS_PERSON_2009_1
		    )
		  WHERE RNUM=1
		  ) SUB_ALP2009
		WHERE P.AGEP>=18
		AND P.PID    =PI.PID
		AND P.HID    =H.HID
		AND P.PID    = SUB_ALP2009.PID
		AND P.HID    =SUB_ALP2009.HID
		AND ROWNUM  <=100;
